/** Script ACLs do not delete 
 read=nobody 
write=nobody
execute=authenticated 
  **/ 
 /*#*beginblockly*#*<xml xmlns="http://www.w3.org/1999/xhtml"><block type="scriptr_return" id="1" inline="false" x="-185" y="101"><value name="return"><block type="scriptr_callhttp" id="2" inline="false"><field name="url">https://api.scriptr.io/test01</field><field name="method">GET</field><value name="parameters"><block type="lists_create_with" id="3" inline="false"><mutation items="5"></mutation><value name="ADD0"><block type="list_dict" id="4" inline="true"><field name="KEY">start</field><value name="myVALUE"><block type="math_number" id="5"><field name="NUM">0</field></block></value></block></value><value name="ADD1"><block type="list_dict" id="6" inline="true"><field name="KEY">end</field><value name="myVALUE"><block type="math_number" id="7"><field name="NUM">22</field></block></value></block></value><value name="ADD2"><block type="list_dict" id="8" inline="true"><field name="KEY">sQuery</field><value name="myVALUE"><block type="text" id="9"><field name="TEXT">scriptr.io video</field></block></value></block></value><value name="ADD3"><block type="list_dict" id="10" inline="true"><field name="KEY">apsws.time</field><value name="myVALUE"><block type="text" id="11"><field name="TEXT">1426284484144</field></block></value></block></value><value name="ADD4"><block type="scriptr_jsonparse" id="32" inline="true"><field name="key">key</field><value name="jsonString"><block type="math_number" id="33"><field name="NUM">0</field></block></value></block></value></block></value><value name="headers"><block type="lists_create_with" id="12" inline="false"><mutation items="2"></mutation><value name="ADD0"><block type="list_dict" id="13" inline="true"><field name="KEY">Authorization</field><value name="myVALUE"><block type="text" id="14"><field name="TEXT">bearer TDIyODI2REM5MTpzY3JpcHRyOjBCMERBNzgyOTRFRTQwODI0RjdGM0ZGMjU5QzgwREVG</field></block></value></block></value><value name="ADD1"><block type="list_dict" id="15" inline="true"><field name="KEY">Pragma</field><value name="myVALUE"><block type="text" id="16"><field name="TEXT">no-cache</field></block></value></block></value></block></value></block></value></block><block type="logic_null" id="48" x="494" y="122"></block></xml>*#*#*/
return require("http").request({"url": "https://api.scriptr.io/test01" , "method": "GET", "params": {"start": "0",
	"end": "22",
	"sQuery": "scriptr.io video",
	"apsws.time": "1426284484144"}, "headers": {"Authorization": "bearer TDIyODI2REM5MTpzY3JpcHRyOjBCMERBNzgyOTRFRTQwODI0RjdGM0ZGMjU5QzgwREVG","Pragma": "no-cache"}})
null;
   							